from django.urls import path
from . import views

app_name = 'admin_panel_app'

urlpatterns = [
    path('admin/login/', views.admin_login, name='admin_login'),
    path('admin/logout/', views.admin_logout, name='admin_logout'),
    path('admin/dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('admin/carousel/', views.carousel_management, name='carousel_management'),
    path('admin/carousel/create/', views.carousel_create, name='carousel_create'),
    path('admin/carousel/<int:pk>/update/', views.carousel_update, name='carousel_update'),
    path('admin/carousel/<int:pk>/delete/', views.carousel_delete, name='carousel_delete'),
    path('admin/category/', views.category_management, name='category_management'),
    path('admin/category/create/', views.category_create, name='category_create'),
    path('admin/category/<int:pk>/update/', views.category_update, name='category_update'),
    path('admin/category/<int:pk>/delete/', views.category_delete, name='category_delete'),
    path('admin/service/', views.service_management, name='service_management'),
    path('admin/service/create/', views.service_create, name='service_create'),
    path('admin/service/<int:pk>/update/', views.service_update, name='service_update'),
    path('admin/service/<int:pk>/delete/', views.service_delete, name='service_delete'),
    path('admin/team/', views.team_management, name='team_management'),
    path('admin/team/create/', views.team_member_create, name='team_member_create'),
    path('admin/team/<int:pk>/update/', views.team_member_update, name='team_member_update'),
    path('admin/team/<int:pk>/delete/', views.team_member_delete, name='team_member_delete'),
     path('admin/about/', views.about_management, name='about_management'),
    path('admin/about/create/', views.about_create, name='about_create'),
    path('admin/about/<int:pk>/update/', views.about_update, name='about_update'),
    path('admin/about/<int:pk>/delete/', views.about_delete, name='about_delete'),
    path('admin/joint-venture/', views.joint_venture_management, name='joint_venture_management'),
    path('admin/joint-venture/create/', views.joint_venture_create, name='joint_venture_create'),
    path('admin/joint-venture/update/<int:pk>/', views.joint_venture_update, name='joint_venture_update'),
    path('admin/joint-venture/delete/<int:pk>/', views.joint_venture_delete, name='joint_venture_delete'),
    path('contact-info/', views.contact_info_update, name='contact_info_update'),
    path('admin/crop-cycle/', views.crop_cycle_update, name='crop_cycle_update'),
    path('admin/irrigation/', views.irrigation_update, name='irrigation_update'),
    path('admin/extreme-weather/', views.extreme_weather_update, name='extreme_weather_update'),
    path('admin/livestock/', views.livestock_update, name='livestock_update'),
    path('admin/service-bulletin/', views.service_bulletin_update, name='service_bulletin_update'),
    path('admin/automation/', views.automation_update, name='automation_update'),
    path('agromet-product/', views.agromet_product_update, name='agromet_product_update'),
    path('admin/crop-weather-calender/', views.crop_weather_calender_update, name='crop_weather_calender_update'),
    path('admin/remote-sensing/', views.remote_sensing_update, name='remote_sensing_update'),
     path('admin/geo-info/', views.geo_info_update, name='geo_info_update'),
    path('admin/pest-disease/', views.pest_disease_update, name='pest_disease_update'),
    path('admin/guidance/', views.guidance_update, name='guidance_update'),
    path('admin/agromet-adaption/', views.agromet_adaption_update, name='agromet_adaption_update'),
    path('admin/weather-station/', views.weather_station_update, name='weather_station_update'),
    path('admin/web-portal/', views.web_portal_update, name='web_portal_update'),
    path('admin/web-development/', views.web_development_update, name='web_development_update'),
    path('admin/ai-solution/', views.ai_solution_update, name='ai_solution_update'),
    path('admin/it-consultancy/', views.it_consultancy_update, name='it_consultancy_update'),
    path('admin/news-update/', views.news_update_manage, name='news_update_manage'),
    path('admin/news-update/edit/<int:pk>/', views.news_update_edit, name='news_update_edit'),
    path('admin/news-update/delete/<int:pk>/', views.news_update_delete, name='news_update_delete'),
]